resources:
- rbac.yaml
- k8s.yaml
images:
- name: builds-registry.ystack.svc.cluster.local/yolean/gke-node-termination-handler
  newName: docker.io/yolean/k8s-node-termination-handler
  newTag: a4b3d456e286a876fb3f1d921945a6548992aff8@sha256:b23d4f3d1efa56c1c9db5557c2fd21a2dbf97a12e737755451f2b2d1a8b073ae
